typography_spectrum: 0.9409778302069753
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cbcbcb'
    - '#8f8f8f'
    - '#454545'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.38327
analytics:
  google: null
  facebook: null
  twitter: null
name: bayview baptist
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello World
purpose: []
