name: bayview baptist
favicon: null
layout_spectrum: 0.18543
typography_spectrum: 0.9409778302069753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cbcbcb'
    - '#8f8f8f'
    - '#454545'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5653519816696644
  rhythmicContrast: 0.75
purpose: []
