name: bayview baptist
favicon: null
layout_spectrum: 0.38327
typography_spectrum: 0.9409778302069753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cbcbcb'
    - '#8f8f8f'
    - '#454545'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
